# Generated by Django 2.2.6 on 2019-10-22 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20191022_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='issued_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='catalog.Student'),
        ),
    ]
