# Generated by Django 2.2.6 on 2019-10-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20191022_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(blank=True, help_text='Add a author', related_name='copies', to='catalog.Author'),
        ),
    ]
