# Generated by Django 2.2.6 on 2019-10-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20191019_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='number_of_copies',
            field=models.IntegerField(default=0, help_text='Number of copies of this book. Readonly Field'),
        ),
    ]
