# Generated by Django 2.2.6 on 2019-11-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20191023_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(blank=True, help_text='Choose a genre for this book.', related_name='books', to='catalog.Genre'),
        ),
    ]
