# Generated by Django 2.2.6 on 2019-11-15 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20191115_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['issued_on'], 'verbose_name': 'Copy', 'verbose_name_plural': 'Book Copies'},
        ),
        migrations.RenameField(
            model_name='bookinstance',
            old_name='due_back',
            new_name='issued_on',
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='issued_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
