# Generated by Django 2.2.6 on 2019-10-20 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20191020_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_shelf',
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='shelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Shelf'),
        ),
    ]
